define

chemical-gene-interaction sub relation,
#    relates interacting-gene,
#    relates interacting-chemical,
    relates from-actor,
    relates to-actor,
    relates data-source,
    plays from-actor,
    plays to-actor,
    has degree,
    key identifier,
    has text;

pmid sub attribute,
    datatype long;

degree sub attribute,
    datatype string;  # TODO Add regex

identifier sub attribute,
    datatype string;

text sub attribute,
    datatype string;

chemical sub entity,
    key identifier,
#    plays interacting-chemical;
    plays from-actor,
    plays to-actor;

gene sub entity,
    key identifier,
#    plays interacting-gene;
    plays from-actor,
    plays to-actor;

pubmed-citation sub entity,
    key pmid,
    plays data-source;

#identifier sub attribute,
#  datatype string;
#
#disease sub entity,
#    has identifier;
#
#
## chemical-disease interaction types:
#
#chemical-disease-interaction sub relation,
#    relates interacting-chemical,
#    relates interacting-disease;
#
#abundance sub chemical-disease-interaction;
## The abundance of a chemical (if chemical synthesis is not known).
#
#activity sub chemical-disease-interaction;
## An elemental function of a molecule.
#
#binding sub cdi;
## A molecular interaction.
#
#cotreatment sub cdi;
## Involving the use of two or more chemicals simultaneously.
#
#expression sub cdi;
## The expression of a gene product.